### ISSUE TITLE
Request exact steps and the order to run the 5 models

### ISSUE THREAD

**Issue by webservicereco** [molecularsets/moses#65] opened 2019-12-14 17:07 UTC
Since there are many .py files across several folders, could you pl. share steps to execute the 5 models? I have been able to download most libraries including torch 1.1.0, etc. I am running into below errors. Clearly I am not running it the way it is supposed to be run. Could you kindly shed some light on this?
MOSES: Not knowing which py file to run in Jupyter notebook 6.0.3, I tried to execute individual model files. (i) I could run config.py, model.py, and train.py in 4 out of 5 models (except latentgan).  In Latentgan, ran into issues with (i) ddc_pub v3 (https://github.com/pcko1/Deep-Drug-Coder/blob/master/ddc_pub/ddc_v3.py), (ii) with molvecgen, and (iii) with Metrics (ModuleNotFoundError: No module named '_main.utils'; 'main' is not a package), Utils (NameError: name 'file_' is not defined).I also ran into this error "ModuleNotFoundError    Traceback (most recent call last)<ipython-input-32-2a337ac27c99> in <module>
     35 
     36 # Custom dependencies
---> 37 from .vectorizers import SmilesVectorizer
     38 from .generators import CodeGenerator as DescriptorGenerator
     39 from .generators import HetSmilesGenerator

**Comment by danpol** [comment] 2020-02-10 11:26
Hi, @webservicereco. I'm closing this issue as a duplicate of #66

**Closed by danpol** 2020-02-10 11:26 UTC
